# Generated by Django 3.0.7 on 2020-09-29 13:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=datetime.datetime(2020, 9, 29, 13, 23, 0, 144667, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
    ]
